### PR TITLE
fix: integration with user webpack configs

### PR DESCRIPTION
**Pull request by xfumihiro**
The plugin wasn't passing all options to user's webpack config & was blocking it in dev mode.

### CODE REVIEW

**Comment by hanford** [comment]
@xfumihiro can you explain a circumstance where we need this? just want to be 💯 before merging.

Thanks for the contribution btw!

**Comment by xfumihiro** [comment]
@hanford So that people can use this plugin with other webpack configs:

```js
module.exports = withOffline({
  webpack: (config, { dev, isServer }) => {
    if (ANALYZE) {
      config.plugins.push(
        new BundleAnalyzerPlugin({
          analyzerMode: 'server',
          analyzerPort: isServer ? 8888 : 8889,
          openAnalyzer: true,
        })
      )
    }

    if (dev) {
      config.module.rules.push({
        test: /\.js$/,
        enforce: 'pre',
        exclude: /node_modules/,
        loader: 'eslint-loader',
        options: {
          // Emit errors as warnings for dev to not break webpack build.
          // Eslint errors are shown in console for dev, yay :-)
          emitWarning: dev,
        },
      })
    }
    config.resolve.modules.unshift(path.resolve(__dirname))
    return config
  },
})
```

**Comment by xfumihiro** [comment]
Oops! didn't see that there already merging user's config in [here](https://github.com/hanford/next-offline/blob/master/index.js#L41)
Somehow the integration with material-ui isn't working...

**Comment by xfumihiro** [comment]
Ahh. I think we should pass in all options like this:
```js
nextConfig.webpack(config, { buildId, dev, ...options })
```
otherwise it won't work

**Comment by hanford** [comment]
@xfumihiro, just left work .. will do another pass tomorrow!

**Comment by xfumihiro** [comment]
@hanford no problem!

**Comment by xfumihiro** [comment]
The plugin wasn't passing all options to user's webpack config & was blocking it in dev mode.

**Comment by hanford** [comment]
thanks @xfumihiro ! I've deployed a patch version `2.1.1` which includes this fix. I verified it previously wasn't working with material ui and your fix works!

An environment with service workers and material ui can be seen here: https://with-material-ui-gjvihrzejr.now.sh/

**Pull request merged**
