### PR TITLE
Only add files necessary for npm registry

### PR DESCRIPTION
**Pull request by raajnadar**
## Motivation

Add only necessary files in npm registery.

https://docs.npmjs.com/files/package.json#files

## Test plan

Publish to npm into canary/next so that we can test if all the necessary files are included in npm registry.

### CODE REVIEW

**Comment by hanford** [comment]
Thanks for the contribution!

**Comment by hanford** [comment]
live in version `4.0.2`!

**Comment by raajnadar** [comment]
I will test in my local project..

**Comment by hanford** [comment]
@raajnadar I've already tested in a few of mine, but please let me know!

**Comment by raajnadar** [comment]
Tested and everything is OK!

**Pull request merged**
