### PR TITLE
rename static -> public & fix tests

### PR DESCRIPTION
**Pull request by JipSterk**
this pullrequest fixes the following issues: 
* #201 
* #203 
* #171
* #141

### CODE REVIEW

**Comment by hanford** [comment]
Awesome, should be able to take a look sometime today or tomorrow!

**Comment by allenylzhou** [comment]
What version of next-offline do I have to install to try out these fixes?

**Comment by hanford** [comment]
@allenylzhou I merged this and released version `next-offline@5.0.0-beta.9` but noticed some problems on my personal website so I reverted one of the changes, and released version `next-offline@5.0.0-beta.10`

Can you give both a try and report back your experience?

**Comment by hanford** [comment]
@JipSterk I had tot revert this d16b381812ba8ecc623f7b792c86ff2956c97bb8 to fix offline on my personal website, any ideas?

**Comment by derekdowling** [comment]
Is this backwards compatible for apps that are still on `static`? If not, this should really be a 6.0 release since it is a big breaking change, especially for apps that need to be more careful about migrating.

**Comment by derekdowling** [comment]
My mistake, I see that specific change was reverted. That'd be a real subtle break for everyone not on `public` yet.

**Pull request merged**
